name = "KruSMP"
author = "KruKnight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e6fd85043f731da52bd0da4457f14eb2e71f949df6de056b918f56be82f5f64"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
