name = "KruSMP"
author = "KruKnight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60eaa669e726aac02fa07839dfaaa10072b41f6d9ac2047f0f510d853981ad6c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
