name = "KruSMP"
author = "KruKnight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd71a46649d65f27f8547931cfc3fcaf07dec06dd8c28fc49aa46e6dd91c6194"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
